### ISSUE TITLE
How to train further with my own code

### ISSUE THREAD

**Issue by yutaixi** [bigcode-project/starcoder#110]
My company has some projects code，i want to train the starcoder with these code ,so that it can write code sytle like my own projects.

**Comment by ArmelRandy** [comment]
Hi. This code is design to fine-tune StarCoder on any task that can be phrased as a text-to-text mapping. For example, if you have a dataset with contains multiple functions written in 2 different styles, you can fine-tune StarCoder (with this code) on this dataset in order to make it learn sort of a `style matching`.

**Comment by yutaixi** [comment]
what is the text-to-text mapping file like?Any guide example ？

**Comment by ArmelRandy** [comment]
I meant, you just have to create a dataset with 2 columns (or more, you will just have to indicate the columns of interest when using this script with the arguments `input_column_name` and `output_column_name`). The first column could contain for example a code written with style 1, and the second column should contain a code written with style 2.

This [dataset](https://huggingface.co/datasets/ArmelR/stack-exchange-instruction) can be used to fine-tune StarCoder in order to map the column `question` to the column `response`. You will have to create a dataset with a similar format. You can refer to [this](https://huggingface.co/docs/datasets/create_dataset) for more information about how to create a HF dataset and push it on the hub.

**Comment by yutaixi** [comment]
![image](https://github.com/bigcode-project/starcoder/assets/10369231/0000ff3e-4f11-442f-bd39-b30dfecf5369)

When the text-to-text mapping file is ready , should i put it in this path 'data/finetune' ？

**Comment by yutaixi** [comment]
When the text-to-text mapping file is ready, pushing it to the hub is a must or i can use it locally?How to use it locally

**Comment by yutaixi** [comment]
> I meant, you just have to create a dataset with 2 columns (or more, you will just have to indicate the columns of interest when using this script with the arguments `input_column_name` and `output_column_name`). The first column could contain for example a code written with style 1, and the second column should contain a code written with style 2.
> 
> This [dataset](https://huggingface.co/datasets/ArmelR/stack-exchange-instruction) can be used to fine-tune StarCoder in order to map the column `question` to the column `response`. You will have to create a dataset with a similar format. You can refer to [this](https://huggingface.co/docs/datasets/create_dataset) for more information about how to create a HF dataset and push it on the hub.

@ArmelRandy Thank you so much
