### ISSUE TITLE
Does it work for sql generation?

### ISSUE THREAD

**Issue by nlp-focus** [bigcode-project/starcoder#33]
![image](https://github.com/bigcode-project/starcoder/assets/68825814/cc863860-9f77-41a4-bc1a-be7d949e3866)
I tried but it just repeats the prompts.

**Comment by loubnabnl** [comment]
This can happen since it isn't an instruction model it does better at code completion so you would rewrite you instruction as a comment and start the SQL code and let it complete it or you could try this instruction-tuned version of the model: https://huggingface.co/spaces/HuggingFaceH4/starchat-playground

**Comment by brainwavecoder9** [comment]
The [starchat-alpha blog post](https://huggingface.co/blog/starchat-alpha) explains why you're not getting the results you are looking for (and also provides an example of their **StarChat** solution which I think would do what you are hoping for and is what @loubnabnl referenced).
